### ISSUE TITLE
Clicking on floor 7 when adding an elevator actually just adds an elevator

### ISSUE THREAD

**Issue by ad1217** [WPI-CS3733-C17-Gamma/project-pather#63]
Should be able to select floors with shift, but apperently there is some onclick wierdness.

**Comment by iwwoods** [comment]
In addition to this, selecting items in the menu don't correlate to what items are actually selected.
(It is written so that clicking on an option adds it to the selected list, not selecting the option)

**Comment by iwwoods** [comment]
Adam, you should mark this as resolved
