### ISSUE TITLE
MapAdminDisplay menu is covered by nodes

### ISSUE THREAD

**Issue by SaahilClaypool** [WPI-CS3733-C17-Gamma/project-pather#77]

**Comment by ad1217** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Issues (under git issues) from I2](https://trello.com/c/TojWFYZb/15-fix-issues-under-git-issues-from-i2)

**Comment by ad1217** [comment]
Closed by dc3e56024905af9b4229bde47fac3580a89d087d.
